spring:
  freemarker:
    cache: false
  devtools:
    livereload:
      enabled: true
  thymeleaf:
        cache: false
  
  datasource:
      url: "jdbc:mariadb://localhost:3306/Diary"
      username: root
      password: dlalsgh123
  jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
                format_sql: true
  jackson:
    time-zone: UTC
    serialization:
                  WRITE_DATES_AS_TIMESTAMPS : false
                  
logging:
        level:
              com:
                  devson: 
                          pagination: debug
                          
server:
    port: 8080
    servlet:
        cookie:
          http-only: true
        session:
         tracking-modes: cookie

moimImagePath: C:/dayary/moim/image

app:
      jwtSecret : JWTSuperSecretKey
      jwtExpirationInMs : 604800000